const WEATHER_CODE_MAP: Record<number, string> = {
  0: "/icons/sun.png",
  1: "/icons/sun.png",
  2: "/icons/cloudy.png",
  3: "/icons/very-cloudy.png",
  45: "/icons/foggy.png",
  48: "/icons/foggy.png",
  51: "/icons/rain.png",
  53: "/icons/rain.png",
  55: "/icons/rain.png",
  56: "/icons/rain.png",
  57: "/icons/rain.png",
  61: "/icons/rain.png",
  63: "/icons/rain.png",
  65: "/icons/rain.png",
  66: "/icons/rain.png",
  67: "/icons/rain.png",
  71: "/icons/snowfall.png",
  73: "/icons/snowfall.png",
  75: "/icons/snowfall.png",
  77: "/icons/snowfall.png",
  80: "/icons/rain.png",
  81: "/icons/rain.png",
  82: "/icons/rain.png",
  85: "/icons/snowfall.png",
  86: "/icons/snowfall.png",
  95: "/icons/thunderstorm.png",
  96: "/icons/thunderstorm.png",
  99: "/icons/thunderstorm.png",
};

export { WEATHER_CODE_MAP };
